[package]
license = "MIT"
name = "nonpoison_serde"
version = "0.1.0"
edition = "2024"
description = "An implementation of Serde for std::sync::nonpoison::Mutex"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
rand = "0.9.2"
serde_json = "1.0.145"
